modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/frqnny/dark-enchanting"
license = "LGPL-3.0"

[[mods]]
modId = "darkenchanting"
version = "${version}"
displayName = "Dark Enchanting"
authors = "Frqnny"
description = '''
Control your enchantments, at a price!
'''
logoFile = "icon.png"

[[dependencies.darkenchanting]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.darkenchanting]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.darkenchanting]]
modId = "architectury"
type = "required"
versionRange = "[13.0.1,)"
ordering = "AFTER"
side = "BOTH"
